name: Build Docker, and publish to Developer K8s
on:
  push:
    branches: [docker-example]
permissions:
  id-token: write
  contents: read
jobs:
  jobName:
    name: Build Docker image and Push to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: "127.0.0.1"
          FILE_OVPN: ".github/vpn/config.ovpn"
        env:
          CA_CRT: ${{ secrets.APP041_OVNP_CA}}
          USER_CRT: ${{ secrets.APP041_OVNP_CERT }}
          USER_KEY: ${{ secrets.APP041_OVNP_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::859821442994:role/SKFLAM_GithubActions
          role-session-name: github-actions-session
          aws-region: us-east-1
      - uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.APP041_ACCOUNT_ID }}
          repo: skflam-techhub-training
          region: us-east-1
          tags: developer
      - uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          cluster_name: k8-internal-testing
          args: apply -f deploy/deployApplication-developer.yaml
      - uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          cluster_name: k8-internal-testing
          args: rollout restart deployment/skflam-techhub-training -n developer